services:
  mqtt:
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto-data:/mosquitto
      - ./mosquitto/config:/mosquitto/config:ro

volumes:
  mosquitto-data:
